version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - server1
      - server2

  server1:
    build:
      context: ./server
    environment:
      - PORT=50051
    container_name: server1

  server2:
    build:
      context: ./server
    environment:
      - PORT=50052
    container_name: server2
